--create database DDL;

--USE DDL;


--CREATE TABLE TRG_DEPT (
--    ID INT,
--    NAME VARCHAR(25)
--);

--SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'TRG_DEPT';

--CREATE TABLE DEPARTMENTS (
--    ID INT,
--    NAME VARCHAR(25)
--);

--INSERT INTO DEPARTMENTS (ID, NAME) VALUES (1, 'HR'), (2, 'IT'), (3, 'Finance');

--SELECT ID, NAME INTO DEPT101 FROM DEPARTMENTS;

--SELECT * FROM DEPT101;

--CREATE TABLE TRG_EMP (
--    ID INT,
--    LAST_NAME VARCHAR(25),
--    FIRST_NAME VARCHAR(25),
--    DEPT_ID INT
--);

--SELECT * FROM TRG_EMP;

-- ALTER TABLE TRG_EMP ALTER COLUMN LAST_NAME VARCHAR(50);

--SELECT * FROM TRG_EMP;

--CREATE TABLE EMPLOYEES (
--    EMPLOYEE_ID INT,
--    FIRST_NAME VARCHAR(25),
--    LAST_NAME VARCHAR(50),
--    SALARY DECIMAL(10,2),
--    DEPARTMENT_ID INT
--);

--INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID) 
--VALUES 
--(1, 'John', 'Doe', 50000, 1),
--(2, 'Jane', 'Smith', 60000, 2);


--SELECT * FROM EMPLOYEES;

--DROP TABLE TRG_EMP;

--CREATE TABLE TRG_EMPLOYEES (
--    ID INT,
--    FIRST_NAME VARCHAR(25),
--    LAST_NAME VARCHAR(50),
--    SALARY DECIMAL(10,2),
--    DEPT_ID INT
--);

--INSERT INTO TRG_EMPLOYEES (ID, FIRST_NAME, LAST_NAME, SALARY, DEPT_ID)
--SELECT ID, FIRST_NAME, LAST_NAME, SALARY, DEPT_ID FROM TRG_EMPLOYEES;

--EXEC sp_rename 'TRG_EMPLOYEES', 'TRG_emp';


--ALTER TABLE TRG_EMP DROP COLUMN FIRST_NAME;

